### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by loveJasmine** [zhiguowang/BiMPM#29]
(venv) mldl@mldlUB1604:~/ub16_prj/BiMPM$ python src/SentenceMatchTrainer.py --config_path configs/snli.sample.config
Loading the configuration from configs/snli.sample.config
Collecting words, chars and labels ...
Number of words: 35012
Number of chars: 61
word_vocab shape is (35611, 300)
Number of labels: 3
Build SentenceMatchDataStream ... 
Number of instances in trainDataStream: 549367
Number of batches in trainDataStream: 5494
Number of instances in devDataStream: 9842
Number of batches in devDataStream: 99
Traceback (most recent call last):
  File "src/SentenceMatchTrainer.py", line 253, in <module>
    main(FLAGS)
  File "src/SentenceMatchTrainer.py", line 175, in main
    is_training=True, options=FLAGS, global_step=global_step)
  File "/home/mldl/ub16_prj/BiMPM/src/SentenceMatchModelGraph.py", line 10, in __init__
    self.create_model_graph(num_classes, word_vocab, char_vocab, is_training, global_step=global_step)
  File "/home/mldl/ub16_prj/BiMPM/src/SentenceMatchModelGraph.py", line 97, in create_model_graph
    is_training=is_training, dropout_rate=options.dropout_rate, use_cudnn=options.use_cudnn)
  File "/home/mldl/ub16_prj/BiMPM/src/layer_utils.py", line 20, in my_lstm_layer
    name="{}_cudnn_bi_lstm".format(scope_name), dropout=dropout_rate if is_training else 0)
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by loveJasmine** [comment]
works with tf1.5.0
